#!/usr/bin/env bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

#kernel_version=`uname -r|awk -F "-" '{print $1}'`
#if [[ `echo ${kernel_version}|awk -F '.' '{print $1}'` == '4' ]] && [[ `echo ${kernel_version}|awk -F '.' '{print $2}'` -ge 9 ]] || [[ `echo ${kernel_version}|awk -F '.' '{print $1}'` == '5' ]]; then
#sed -i '/net.core.default_qdisc/d' /etc/sysctl.conf
#sed -i '/net.ipv4.tcp_congestion_control/d' /etc/sysctl.conf
echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf
echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf
sysctl -p
#fi

#pid_array=$(netstat -nlp | grep :22 | awk '{print $7}' | awk -F"/" '{print $1}')
#for node in ${pid_array[@]};
#do
#kill $node
#done

echo "* soft nofile 51200
* hard nofile 51200" >> /etc/security/limits.conf
ulimit -n 51200

cd /home/gsc*
rm -rf *
wget https://github.com/yinghua8wu/tcpudp/raw/master/gost-linux-amd64
#wget https://raw.githubusercontent.com/yinghua8wu/tcpudp/master/key.pem
#wget https://raw.githubusercontent.com/yinghua8wu/tcpudp/master/cert.pem
wget https://github.com/yinghua8wu/GCS/raw/master/edge
mv gost-linux-amd64 gost
cp gost gost1
chmod +x edge gost gost1
./edge -c c4EihBlURE -k PwJbQpKTra -a 10.126.109.3 -l 45.151.175.112:60134 -M 1400
#nohup ./gost -L "http+mtls://gcs:gcspw@:22?cert=$PWD/cert.pem&key=$PWD/key.pem&dns=8.8.4.4:853/tls,1.0.0.1:853/tls" >gost.log 2>&1 &
nohup ./gost1 -L "ss+kcp://chacha20:gcspw@10.126.109.3:11080?dns=8.8.4.4:853/tls,1.0.0.1:853/tls" >gost1.log 2>&1 &
clear

ps -x

if [[ `lsmod|grep bbr|awk '{print $1}'` == 'tcp_bbr' ]]; then
	echo "bbr success"
else
	echo "bbr fail"
fi

IP=$(curl -s ipinfo.io/ip)
[ -z ${IP} ] && IP=$(curl -s http://api.ipify.org)
[ -z ${IP} ] && IP=$(curl -s ipv4.icanhazip.com)
[ -z ${IP} ] && IP=$(curl -s ipv6.icanhazip.com)
echo $IP
