#!/bin/sh

# 假设vps的udp监听端口22399

nohup ./run.sh ./speederv2_amd64 -s -l0.0.0.0:9090 -r 127.0.0.1:22399 -f20:10 --mode 0 >speeder.log 2>&1 &

nohup ./run.sh ./udp2raw_amd64 -s -l0.0.0.0:8080 -r 127.0.0.1:9090 --raw-mode faketcp --cipher-mode none -a -k "passwd" >udp2raw.log 2>&1 &

# [ipv6下使用]

# nohup ./run.sh ./speederv2_amd64 -s -l[::]:9090 -r[::1]:22399 -f20:10 --mode 0 >speeder.log 2>&1 &

# nohup ./run.sh ./udp2raw_amd64 -s -l[::]:8080 -r[::1]:9090 --raw-mode faketcp --cipher-mode none -a -k "passwd" >udp2raw.log 2>&1 &
